package com.chrisom.sisinv.entity;
// Generated 02-ago-2015 18:14:48 by Hibernate Tools 3.4.0.CR1

/**
 * NotaRemisionDetalle generated by hbm2java
 */
public class NotaRemisionDetalle implements java.io.Serializable {

	private NotaRemisionDetalleId id;
	private Productos productos;
	private NotaRemision notaRemision;

	public NotaRemisionDetalle() {
	}

	public NotaRemisionDetalle(NotaRemisionDetalleId id, Productos productos, NotaRemision notaRemision) {
		this.id = id;
		this.productos = productos;
		this.notaRemision = notaRemision;
	}

	public NotaRemisionDetalleId getId() {
		return this.id;
	}

	public void setId(NotaRemisionDetalleId id) {
		this.id = id;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public NotaRemision getNotaRemision() {
		return this.notaRemision;
	}

	public void setNotaRemision(NotaRemision notaRemision) {
		this.notaRemision = notaRemision;
	}

}
