package com.chrisom.sisinv.entity;
// Generated 09-ago-2015 19:16:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NotaRemision generated by hbm2java
 */
public class NotaRemision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7719128964041487555L;
	private Integer id;
	private Vendedor vendedor;
	private Date fecha;
	private double total;
	private Set<NotaRemisionDetalle> notaRemisionDetalles = new HashSet<NotaRemisionDetalle>(0);

	public NotaRemision() {
	}

	public NotaRemision(Vendedor vendedor, Date fecha, double total) {
		this.vendedor = vendedor;
		this.fecha = fecha;
		this.total = total;
	}

	public NotaRemision(Vendedor vendedor, Date fecha, double total, Set<NotaRemisionDetalle> notaRemisionDetalles) {
		this.vendedor = vendedor;
		this.fecha = fecha;
		this.total = total;
		this.notaRemisionDetalles = notaRemisionDetalles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	public Set<NotaRemisionDetalle> getNotaRemisionDetalles() {
		return this.notaRemisionDetalles;
	}

	public void setNotaRemisionDetalles(Set<NotaRemisionDetalle> notaRemisionDetalles) {
		this.notaRemisionDetalles = notaRemisionDetalles;
	}

}
