package com.chrisom.sisinv.entity;
// Generated 09-ago-2015 19:16:00 by Hibernate Tools 3.4.0.CR1

/**
 * NotaRemisionDetalle generated by hbm2java
 */
public class NotaRemisionDetalle implements java.io.Serializable {

	private NotaRemisionDetalleId id;
	private Producto productos;
	private NotaRemision notaRemision;

	public NotaRemisionDetalle() {
	}

	public NotaRemisionDetalle(NotaRemisionDetalleId id, Producto productos, NotaRemision notaRemision) {
		this.id = id;
		this.productos = productos;
		this.notaRemision = notaRemision;
	}

	public NotaRemisionDetalleId getId() {
		return this.id;
	}

	public void setId(NotaRemisionDetalleId id) {
		this.id = id;
	}

	public Producto getProductos() {
		return this.productos;
	}

	public void setProductos(Producto productos) {
		this.productos = productos;
	}

	public NotaRemision getNotaRemision() {
		return this.notaRemision;
	}

	public void setNotaRemision(NotaRemision notaRemision) {
		this.notaRemision = notaRemision;
	}

}
